blogsite/urls.py
from django.urls import path

from . import views

app_name = "blogsite"
urlpatterns = [
        path("", views.index, name="index"),
        path("article/", views.article, name="article"),
        path("<slug:slug>/detail/", views.detail, name="detail"),
        path("contact/", views.contact, name="contact"),
        path("about/", views.about, name="about"),
        path("stat/", views.stat, name='stat'),
        path("com/", views.com, name="com"),
        path("pop/", views.pop, name="pop")
]

testdjango/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from CustomAdmin.admin import admin_site

handler404 = 'blogsite.views.Erreur404'
handler400 = 'blogsite.views.Erreur400'
handler500 = 'blogsite.views.Erreur500'

for model, _ in admin.site._registry.items():
    admin_site.register(model)

urlpatterns = [
    path('admin/', admin_site.urls),
    path('', include("blogsite.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogsite/models/articleModel.py
from django.db import models


class Contenu(models.Model):
    contentTitle = models.CharField(max_length=200)
    paragraphe_1 = models.TextField()
    paragraphe_2 = models.TextField()
    paragraphe_3 = models.TextField()
    citation = models.TextField()
    citation_auteur = models.CharField(max_length=200)

    def __str__(self): 
        return self.contentTitle



class GeneralInformation(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    content = models.OneToOneField(
        Contenu,
        on_delete = models.CASCADE,
        primary_key = True,
    )
    contexte = models.CharField(max_length=2000)
    slug = models.SlugField(default="",null=False)

    class Meta:
        abstract = True

class Categorie(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=2000)

    def __str__(self):
        return self.title
    
class Article(GeneralInformation):
    mod_date = models.DateTimeField("date modified")
    categories = models.ManyToManyField(Categorie)
    featured = models.BooleanField()
    popular = models.IntegerField()
    image = models.ImageField(upload_to="images/")
    image_illus = models.ImageField(upload_to="images/")
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class Page(GeneralInformation):
    def __str__(self):
        return self.title

blogsite/models/formModel.py
from django.db import models

class Utilisateur(models.Model):
    mail = models.TextField(max_length=100)
    def __str__(self):
        return self.mail
    
class Contact(models.Model):
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    tel = models.CharField(max_length=20)
    sujet = models.CharField(max_length=1000)
    message = models.TextField()
    def __str__(self):
        return self.sujet

class Test(models.Model):
    upload = models.FileField(upload_to="blogsite/static/blog/images ")

class StatUser(models.Model):
    date_debut = models.CharField(max_length=100)
    date_fin = models.CharField(max_length=100)
    int_debut = models.IntegerField()
    int_fin = models.IntegerField()

blogsite/forms.py
from django import forms
from .models import Utilisateur, Contact, Article
from django.forms import EmailInput, ModelForm, TextInput, Textarea

class MailForm(ModelForm):
    class Meta:
        model = Utilisateur
        fields = ['mail']
        widgets = {
            'mail' : EmailInput(attrs={
                'class': "text-black w-96 rounded-lg",
                'placeholder':"Entrez votre e-mail"
            })
        }

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['nom', 'prenom', 'tel', 'sujet', 'message']
        widgets = {
            'nom' : TextInput(attrs = {
                'style':"max-width:500px;",
                'placeholder':"Nom",
            }),
            'prenom' : TextInput(attrs = {
                'style':"max-width:500px;",
                'placeholder':"Prénom",
            }),
            'tel' : TextInput(attrs = {
                'style':"max-width:300px;",
                'pattern':"[0-9]{2} [0-9]{2} [0-9]{2} [0-9]{2} [0-9]{2}",
                'placeholder':"Tél (ex : 01-02-03-04-05)",
            }),
            'sujet' : TextInput(attrs = {
                'style':"max-width:300px;",
                'placeholder':"Sujet du message",
            }),
            'message' : Textarea(attrs = {
                'style':"max-width:500px;",
                'placeholder':"Message",
            })


        }

blogsite/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings

import csv
import json


from .models import Article, Utilisateur, Contact, Categorie, StatUser
from .forms import MailForm, ContactForm


def index(request):
    latest_article = Article.objects.order_by("-pub_date")[1:4]
    last_article = Article.objects.order_by("-pub_date")[0:1]
    if len(last_article) != 0 :
        categories_last_article = last_article[0].categories.all()
    else:
        categories_last_article = "None"

    featured_article = Article.objects.filter(featured = 1).values()
    popular_article = Article.objects.order_by("-popular")[:6]
    categoriesID = list(Article.objects.values_list("categories"))
    categories = []

    for i in range(len(categoriesID)):
        a = list(Categorie.objects.raw("SELECT id,title FROM blogsite_categorie WHERE id ="+str(categoriesID[i][0])))
        categories.append(a)


    successForm = request.GET.get('successForm',False)


    if request.method=="POST":
        form = MailForm(request.POST)
        if form.is_valid():
            email = request.POST.get("mail")
            user = Utilisateur(mail=email)
            user.save()

            return redirect("./?successForm=True")

    else : 
        form = MailForm()

    context = {"latest_article" : latest_article, "featured_article": featured_article, "popular_article": popular_article, "last_article":last_article, "categories_last_article":categories_last_article,"form":form, "successForm":successForm, "categories":categories}


    return render(request, "blog/index.html", context)

def detail(request, slug):
    successForm = request.GET.get('successForm',False)
    successLike = request.GET.get('successLike', False)

    popular_article = Article.objects.order_by("-popular")[:3]


    form = MailForm(request.POST)
    if form.is_valid():
        email = request.POST.get("mail")
        user = Utilisateur(mail=email)
        user.save()

        return redirect("./detail/?successForm=True")

    else : 
         form = MailForm()
    
    article = get_object_or_404(Article, slug=slug)

    if article:
        article.views += 1
        article.save()

    if 'like' in request.POST:
        if request.session.get("has_liked" + slug, False):
            article.views -= 2
            return redirect("./?successLike=already")
        article.popular += 1
        article.views -= 2
        article.save()
        request.session["has_liked" + slug] = True
        request.session["has_disliked" + slug] = False

        return redirect("./?successLike=True")
    
    if 'dislike' in request.POST:
        if request.session.get("has_disliked" + slug, False):
            article.views -= 2
            return redirect("./?successLike=already")
        if(article.popular > 0):
            article.popular -= 1
        article.views -= 2
        article.save()
        request.session["has_liked" + slug] = False
        request.session["has_disliked" + slug] = True

        return redirect("./?successLike=True")

    context = {"article": article, "form":form, "successForm":successForm, "successLike":successLike, "popular_article": popular_article, "has_liked": request.session.get("has_liked" + slug), "has_disliked": request.session.get("has_disliked" + slug)}
    return render(request, "blog/detail.html", context)

def article(request):
    successForm = request.GET.get('successForm',False)
    if request.method == 'GET' and request.GET.get('search') != None:
        latest_article = Article.objects.filter(title__icontains=request.GET.get('search'))
    else : 
        latest_article = Article.objects.order_by("-pub_date")

    L = []
    for article in latest_article:
        art = []
        for cat in article.categories.all():
            art.append(cat)
        L.append(art)
        
            

    if request.method=="POST":
        form = MailForm(request.POST)
        if form.is_valid():
            email = request.POST.get("mail")
            user = Utilisateur(mail=email)
            user.save()

            return redirect("./?successForm=True")

    else : 
        form = MailForm()
    
    context = {"articles":latest_article, "form":form, "successForm":successForm, "liste":L}

    return render(request, "blog/article.html", context)

def contact(request):
    success=request.GET.get('success',False)
    successForm = request.GET.get('successForm',False)
    if request.method=="POST":
        formContact = ContactForm(request.POST)
        if formContact.is_valid():

            nom = request.POST.get("nom")
            prenom = request.POST.get("prenom")
            tel = request.POST.get("tel")
            sujet = request.POST.get("sujet")
            message = request.POST.get("message")

            contact = Contact(nom=nom, prenom=prenom, tel= tel, sujet=sujet, message=message)
            contact.save()
            return redirect("./?success=True")


    else : 
        formContact = ContactForm()
    
    if request.method=="POST":
        form = MailForm(request.POST)
        if form.is_valid():
            email = request.POST.get("mail")
            user = Utilisateur(mail=email)
            user.save()

            return redirect("./?successForm=True")

    else : 
        form = MailForm()


    context={"formContact":formContact, "form":form, "success":success, "successForm":successForm}

    return render(request, "blog/contact.html", context)

def about(request):
    successForm = request.GET.get('successForm',False)

    if request.method=="POST":
        form = MailForm(request.POST)
        if form.is_valid():
            email = request.POST.get("mail")
            user = Utilisateur(mail=email)
            user.save()

            return redirect("./?successForm=True")

    else : 
        form = MailForm()

    context={"form":form, "successForm":successForm}

    return render(request,"blog/about.html", context)

def Erreur404(request, exception):
    return render(request, '404.html', status=404)

def Erreur400(request, exception):
    return render(request, '400.html', status=400)

def Erreur500(request):
    return render(request, '500.html', status=500)

def stat(request):
    successForm = request.GET.get('successForm',False)

    fichier_naissance = open(str(settings.BASE_DIR) + "/blogsite/static/blog/naissance_data.csv", encoding="utf-8")
    csvreader_naissance = csv.reader(fichier_naissance)
    print(csvreader_naissance)
    y_naissance= []
    x_naissance = []
    rows_naissance = []

    for row in csvreader_naissance:
        rows_naissance.append(row)
    for r in rows_naissance:
        x_naissance.append(r[0])
        y_naissance.append(r[1])
        

    fichier_naissance.close()
    del(x_naissance[0])
    del(y_naissance[0])

    if request.method=="POST":
        form = MailForm(request.POST)
        if form.is_valid():
            email = request.POST.get("mail")
            user = Utilisateur(mail=email)
            user.save()

            return redirect("./?successForm=True")

    else : 
        form = MailForm()
    
    fichier = open(str(settings.BASE_DIR) + "/blogsite/static/blog/data.csv", encoding="utf-8")
    csvreader = csv.reader(fichier)
    d= []
    rows = []


    for row in csvreader:
        rows.append(row)
    for r in rows:
            d.append([r[3],r[8]])


    fichier.close()
    del(d[0])
    valeur_debut = request.POST.get("valeur_debut",0)
    valeur_fin = request.POST.get("valeur_fin",0)
    int_debut = request.POST.get("int_debut",1)
    int_fin = request.POST.get("int_fin",1)

    if (valeur_debut==0 and valeur_fin==0 and request.session.get("stat", False)):
        info = StatUser.objects.get(id = request.session["statid"])
        valeur_debut= info.date_debut
        valeur_fin = info.date_fin
        int_debut = info.int_debut
        int_fin = info.int_fin

    if request.session.get("stat", False):
        info = StatUser.objects.get(id = request.session["statid"])
        info.date_debut = valeur_debut
        info.date_fin = valeur_fin
        info.int_fin = int_fin
        info.int_debut = int_debut
        info.save()
    else:
        info = StatUser(date_debut=valeur_debut, date_fin = valeur_fin, int_debut = int_debut, int_fin = int_fin)
        info.save()
        request.session["statid"] = list(StatUser.objects.values('id'))[-1]["id"]
        request.session["stat"] = True

    context={"d1":d[:25], "d2":d[25:50],"d3":d[50:75],"d4":d[75:], "form":form, "successForm":successForm, "x_naissance":json.dumps(x_naissance), "y_naissance":json.dumps(y_naissance), "int_debut":int_debut, "int_fin":int_fin, "date_debut":valeur_debut, "date_fin":valeur_fin}
      
    return render(request, "blog/stat.html",context)

def com(request):
    fichier = open(str(settings.BASE_DIR) + "/blogsite/static/blog/data.csv", encoding="utf-8")
    csvreader = csv.reader(fichier)
    d= []
    rows = []

    for row in csvreader:
        rows.append(row)
    for r in rows:
            d.append([r[3],r[6]])

    fichier.close()
    del(d[0])

    context={"d1":d[:25], "d2":d[25:50],"d3":d[50:75],"d4":d[75:]}


    return render(request,"blog/tab-stat/com.html",context)

def pop(request):
    fichier = open(str(settings.BASE_DIR) + "/blogsite/static/blog/data.csv", encoding="utf-8")
    csvreader = csv.reader(fichier)
    d= []
    rows = []

    for row in csvreader:
        rows.append(row)
    for r in rows:
            d.append([r[3],r[8]])
    fichier.close()
    del(d[0])

    context={"d1":d[:25], "d2":d[25:50],"d3":d[50:75],"d4":d[75:]}


    return render(request,"blog/tab-stat/pop.html",context)

blogsite/templates/blog/about.html
{%extends "blog/content-about.html" %}
{% load widget_tweaks %}

{%block header%}
<header>
    <div class="shadow-lg shadow-gris-900 grid xl:grid-cols-3 bg-blanc xl:h-32 top-0 left-0 right-0 place-items-center text-center">
        <div class="w-40 mt-8 justify-self-center">
            <a class="text-xl tracking-wide text-center" href="../">Test Django</a>
        </div>
        <div class="xl:grid xl:grid-rows-2 xl:pt-16 xl:justify-self-end justify-self-center pt-4 place-items-center">
            <div class="align-middle">
                <a href="../article/" class="font-montserrat text-black text-xl tracking-wide px-5 hover:text-primary transition duration-300">Blog</a>
                <a href=" " class="font-montserrat text-black text-xl tracking-wide xl:mx-10 px-5 hover:text-primary transition duration-300">A propos</a>
                <a href="../stat/" class="font-montserrat text-black text-xl tracking-wide xl:mx-10 px-5 hover:text-primary transition duration-300">Statistiques</a>
            </div>
        </div>
        <div class="xl:pt-14 justify-self-center align-middle py-5">
            <a class="w-auto text-center my-auto mx-auto w-auto py-2 px-10 bg-blanc border-primary text-primary font-montserrat rounded-lg inline-block box-border border-2 rounded-x1 hover:bg-primary hover:text-white hover:border-white duration-1000 h-12 font-bold " href="../contact/">Contactez nous</a>
        </div>
        </div>
</header>

{%if successForm%}
            <div class="pt-10">
            <div class="p-4 mb-4 text-sm rounded-lg bg-green-200 text-center" role="alert">
             <span class="font-medium">Succès !</span> Le formulaire a bien été envoyé
            </div>
{%endif%}

{%endblock header%}


{%block footer%}
<footer>
    <div class="text-center bg-gradient-to-r from-violet-700 to-violet-600 text-blanc font-montserrat py-10">
        <h1 class="text-5xl font-bold py-10">S'inscrire à la newsletter</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="pb-5">
                {%render_field form.mail class="text-tertiary w-auto xl:w-96 rounded-lg focus:ring-2 focus:ring-slate-200 focus:border-slate-200 object-fit text-wrap"%}
            </div>
            <input type="submit" value="Soumettre" class="w-auto px-20 bg-inherit border-blanc text-blanc font-montserrat rounded-lg inline-block box-border border-2 rounded-x1 hover:bg-blanc hover:text-primary duration-1000 h-12 font-bold">
        </form>
    </div>
    <div class="text-center bg-blanc font-montserrat py-10">
        <h1 class="font-bold text-3xl">Site Test</h1>
        <div class="flex flex-row text-center pt-10 justify-center gap-5">
            <a href="/" class="hover:text-primary transition duration-300">Accueil</a>
            <a href="../article/" class="hover:text-primary transition duration-300">Blog</a>
            <a href="" class="hover:text-primary transition duration-300">A propos</a>
            <a href="../contact/" class="hover:text-primary transition duration-300">Nous contacter</a>
        </div>
    </div>
</footer>
{%endblock%}

blogsite/templates/blog/article.html
{%extends "blog/content-article.html" %}
{% load widget_tweaks %}

{%block header%}
<header>
    <div class="shadow-lg shadow-gris-900 grid xl:grid-cols-3 bg-blanc xl:h-32 top-0 left-0 right-0 place-items-center text-center">
        <div class="w-40 mt-8 justify-self-center">
            <a class="text-xl tracking-wide text-center" href="../">Test Django</a>
        </div>
        <div class="xl:grid xl:grid-rows-2 xl:pt-16 xl:justify-self-end justify-self-center pt-4 place-items-center">
            <div class="align-middle">
                <a href="" class="font-montserrat text-black text-xl tracking-wide px-5 hover:text-primary transition duration-300">Blog</a>
                <a href="../about/" class="font-montserrat text-black text-xl tracking-wide xl:mx-10 px-5 hover:text-primary transition duration-300">A propos</a>
                <a href="../stat/" class="font-montserrat text-black text-xl tracking-wide xl:mx-10 px-5 hover:text-primary transition duration-300">Statistiques</a>
            </div>
        </div>
        <div class="xl:pt-14 justify-self-center align-middle py-5">
            <a class="w-auto text-center my-auto mx-auto w-auto py-2 px-10 bg-blanc border-primary text-primary font-montserrat rounded-lg inline-block box-border border-2 rounded-x1 hover:bg-primary hover:text-white hover:border-white duration-1000 h-12 font-bold " href="../contact/">Contactez nous</a>
        </div>
        </div>
</header>

{%if successForm%}
            <div class="pt-10">
            <div class="p-4 mb-4 text-sm rounded-lg bg-green-200 text-center" role="alert">
             <span class="font-medium">Succès !</span> Le formulaire a bien été envoyé
            </div>
{%endif%}

{%endblock header%}


{%block footer%}
<footer>
    <div class="text-center bg-gradient-to-r from-violet-700 to-violet-600 text-blanc font-montserrat py-10">
        <h1 class="text-5xl font-bold py-10">S'inscrire à la newsletter</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="pb-5">
                {%render_field form.mail class="text-tertiary w-auto xl:w-96 rounded-lg focus:ring-2 focus:ring-slate-200 focus:border-slate-200 object-fit text-wrap"%}
            </div>
            <input type="submit" value="Soumettre" class="w-auto px-20 bg-inherit border-blanc text-blanc font-montserrat rounded-lg inline-block box-border border-2 rounded-x1 hover:bg-blanc hover:text-primary duration-1000 h-12 font-bold">
        </form>
    </div>
    <div class="text-center bg-blanc font-montserrat py-10">
        <h1 class="font-bold text-3xl">Site Test</h1>
        <div class="flex flex-row text-center pt-10 justify-center gap-5">
            <a href="/" class="hover:text-primary transition duration-300">Accueil</a>
            <a href="../article/" class="hover:text-primary transition duration-300">Blog</a>
            <a href="../about/" class="hover:text-primary transition duration-300">A propos</a>
            <a href="../contact/" class="hover:text-primary transition duration-300">Nous contacter</a>
        </div>
    </div>
</footer>
{%endblock%}

blogsite/templates/blog/contact.html
{%extends "blog/content-contact.html" %}
{% load widget_tweaks %}

{%block header%}
<header>
    <div class="shadow-lg shadow-gris-900 grid xl:grid-cols-3 bg-blanc xl:h-32 top-0 left-0 right-0 place-items-center text-center">
        <div class="w-40 mt-8 justify-self-center">
            <a class="text-xl tracking-wide text-center" href="../">Test Django</a>
        </div>
        <div class="xl:grid xl:grid-rows-2 xl:pt-16 xl:justify-self-end justify-self-center pt-4 place-items-center">
            <div class="align-middle">
                <a href="../article/" class="font-montserrat text-black text-xl tracking-wide px-5 hover:text-primary transition duration-300">Blog</a>
                <a href="../about/" class="font-montserrat text-black text-xl tracking-wide xl:mx-10 px-5 hover:text-primary transition duration-300">A propos</a>
                <a href="../stat/" class="font-montserrat text-black text-xl tracking-wide xl:mx-10 px-5 hover:text-primary transition duration-300">Statistiques</a>
            </div>
        </div>
        <div class="xl:pt-14 justify-self-center align-middle py-5">
            <a class="w-auto text-center my-auto mx-auto w-auto py-2 px-10 bg-blanc border-primary text-primary font-montserrat rounded-lg inline-block box-border border-2 rounded-x1 hover:bg-primary hover:text-white hover:border-white duration-1000 h-12 font-bold " href=" ">Contactez nous</a>
        </div>
        </div>
</header>

{%if successForm%}
            <div class="pt-10">
            <div class="p-4 mb-4 text-sm rounded-lg bg-green-200 text-center" role="alert">
             <span class="font-medium">Succès !</span> Le formulaire a bien été envoyé
            </div>
{%endif%}

{%endblock header%}


{%block footer%}
<footer>
    <div class="text-center bg-gradient-to-r from-violet-700 to-violet-600 text-blanc font-montserrat py-10">
        <h1 class="text-5xl font-bold py-10">S'inscrire à la newsletter</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="pb-5">
                {%render_field form.mail class="text-tertiary w-auto xl:w-96 rounded-lg focus:ring-2 focus:ring-slate-200 focus:border-slate-200 object-fit text-wrap"%}
            </div>
            <input type="submit" value="Soumettre" class="w-auto px-20 bg-inherit border-blanc text-blanc font-montserrat rounded-lg inline-block box-border border-2 rounded-x1 hover:bg-blanc hover:text-primary duration-1000 h-12 font-bold">
        </form>
    </div>
    <div class="text-center bg-blanc font-montserrat py-10">
        <h1 class="font-bold text-3xl">Site Test</h1>
        <div class="flex flex-row text-center pt-10 justify-center gap-10">
            <a href="/" class="hover:text-primary transition duration-300">Accueil</a>
            <a href="../article/" class="hover:text-primary transition duration-300">Blog</a>
            <a href="../about/" class="hover:text-primary transition duration-300">A propos</a>
            <a href="" class="hover:text-primary transition duration-300">Nous contacter</a>
        </div>
    </div>
</footer>
{%endblock%}

blogsite/templates/blog/content-stat.html
{% load static tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{{article.title}}</title>
        <script src="https://d3js.org/d3.v4.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.3/d3.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/topojson/1.6.9/topojson.min.js"></script>
        <script src="{% static 'blog/datamaps.fra.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

        <link rel="stylesheet" href="{% static 'blog/style.css' %}">
        {% tailwind_css %}
    </head>

    <body class="font-montserrat bg-zinc-100">
        {%block header%}
        {%endblock%}

        {{test}}

        <div class="hidden 2xl:flex flex-col place-items-center">
        <h1 class="text-2xl py-3 pt-10">{%if statType == "0"%}Carte de la répartition de la population française{%else%} Carte de la répartition des communes françaises{%endif%}</h1>
        <span class="italic pb-10">Plus un département est foncé, plus il {%if statType == "0"%}est peuplé{%else%}compte de communes{%endif%}</span>
        <div class="flex flex-inline gap-5">
            <div>
            <button id="bt-com" name="vue" value="0" class="text-white end-2.5 bottom-2.5 bg-primary hover:bg-blanc hover:text-primary border hover:border-primary transition duration-1000 focus:ring-4 focus:outline-none focus:ring-primary font-medium rounded-lg text-sm px-4 py-2 ">Vue population</button>
            </div>
        <div class="pb-5">
            <button id="bt-pop" name="vue" value="1" class="text-white end-2.5 bottom-2.5 bg-primary hover:bg-blanc hover:text-primary border hover:border-primary transition duration-1000 focus:ring-4 focus:outline-none focus:ring-primary font-medium rounded-lg text-sm px-4 py-2 ">Vue commune</button>
        </div>
    </div>

        <div id="container" style="position: relative; width: 50%; height: 50%;"></div>
        </div>

        <div id="tab">
            {%include "blog/tab-stat/pop.html"%}
        </div>

        <div class="flex flex-col place-content-center justify-items-center gap-10 pb-10 items-center w-full">
            <h1 class="text-2xl py-3 pt-10">Graphe des naissances mensuels en France depuis 1994</h1>
            <div class="max-w-screen-lg">

            <div>
                <label id="output-range" class="block mb-2 text-sm font-medium text-gray-900">Donnée sélectionnée de {{date_debut}} jusqu'à {{date_fin}}</label>
                <input id="steps-range" type="range" min="0" max="360" value="{{int_fin}}" step="1" class="w-full h-2 bg-purple-200 rounded-lg appearance-none cursor-pointer">
                <input id="steps-range-debut" type="range" min="0" max="360" value="{{int_debut}}" step="1" class="w-full h-2 bg-purple-200 rounded-lg appearance-none cursor-pointer">
            </div>
            
            </div>
            <div class="w-full max-w-screen-lg">
                <canvas id="myChart"></canvas>
            </div>
        </div>


        {%block footer%}
        {%endblock%}
    </body>

    <script>
        /*On définit les variables utilisées dans le fichier JS et qui ont besoin de Jinja pour fonctionner*/
        var data_get_x = {{x_naissance|safe}};
        var data_get_y =  {{y_naissance|safe}}
        var url_stat = "{%url 'blogsite:stat'%}"
        var url_com = "{%url 'blogsite:com'%}"
        var url_pop = "{%url 'blogsite:pop'%}"
        var csrf_tok = '{{csrf_token}}'
    </script>

    <script src="{% static 'blog/stat.js' %}"></script>

    <script>
        var carte
      mapCreate({{statType|safe}}).then(map=>{
        carte = map
       })
    </script>

</html>